version: '3.8'
services:
  mongodb:
    image: mongo:5.0
    container_name: ecommerce-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    container_name: ecommerce-backend
    restart: always
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/
      - MONGO_DB=ecommerce
      - GROQ_API_KEY=YOUR_GROQ_API_KEY
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    container_name: ecommerce-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_BASE=http://localhost:8000

volumes:
  mongo_data:
